name: Community
on: 
  issues:
    types: [opened, edited, milestoned]
  pull_request_target:
    types: [opened, reopened]
  pull_request:
    types: [edited]

jobs:

  labeler:
    runs-on: ubuntu-latest

    steps:
    - name: Check Labels
      id: labeler
      uses: docker://jimschubert/testing:repo-owner-from-fork
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        LOG_LEVEL: "debug"
